FROM amazoncorretto:21-al2023-jdk as BUILD
COPY . /src
WORKDIR /src
# RUN mvn package
RUN ./gradlew build

FROM amazoncorretto:21-al2023-headful
EXPOSE 8080
WORKDIR /app
ARG JAR=spring-petclinic-3.3.0.jar

# COPY --from=BUILD /src/target/$JAR /app.jar
COPY --from=BUILD /src/build/libs/$JAR /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]