name: CI - Container image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    environment: workflow-env
    strategy:
      matrix:
        java: [ '21' ]

    steps:
      - uses: actions/checkout@v4
      - name: Get short SHA
        run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'corretto'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        run: ./gradlew build

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: kathywan/spring-petclinic:${{ env.GHA_SHA }},kathywan/spring-petclinic:latest,kathywan/spring-petclinic:3.3.0-SNAPSHOT
          push: true